- name: Upload to Bale (direct to user)
  env:
    BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
  run: |
    BALE_API="https://api.bale.ai/v1/bot$BOT_TOKEN"
    CHAT_ID="${{ github.event.client_payload.chat_id }}"
    
    if ls part_* 1> /dev/null 2>&1; then
      for file in part_*; do
        curl -F "chat_id=$CHAT_ID" -F "document=@$file" "$BALE_API/sendDocument"
      done
    else
      curl -F "chat_id=$CHAT_ID" -F "document=@${{ steps.file_info.outputs.file }}" "$BALE_API/sendDocument"
    fi
